### ISSUE TITLE
PR #38 - unable to see combat text after locale implementation

### ISSUE THREAD

**Issue by zbrak** [Justw8/NameplateSCT#40]
@Justw8  #38  seems to have broken the addon for me. Unable to see any text in normal mode. I do get text in BlizzardSCT mode.

Reinstalled addon, cleared saved variables. Was working yeterday.

**Comment by Justw8** [comment]
Do you get any errors? since it was working for me with the most recent version.

**Comment by Nikyou** [comment]
Can confirm, the latest version broke something.
1:
```lua
1x AceLocale-3.0-6: NameplateSCT: Missing entry for 'Show Absorbed Damage'
[string "@NameplateSCT/NameplateSCT.lua"]:1265: in main chunk

Locals:
AceAddon = <table> {
 initializequeue = <table> {
 }
 statuses = <table> {
 }
 embeds = <table> {
 }
 frame = AceAddon30Frame {
 }
 addons = <table> {
 }
 enablequeue = <table> {
 }
}
LibEasing = <table> {
 frame = Frame {
 }
}
SharedMedia = <table> {
 OverrideMedia = <table> {
 }
 callbacks = <table> {
 }
 LOCALE_BIT_zhTW = 8
 LOCALE_BIT_ruRU = 2
 MediaType = <table> {
 }
 LOCALE_BIT_western = 128
 MediaTable = <table> {
 }
 LOCALE_BIT_zhCN = 4
 DefaultMedia = <table> {
 }
 MediaList = <table> {
 }
 LOCALE_BIT_koKR = 1
}
L = <table> {
 BlizzardSCT = "BlizzardSCT"
 Auto Attacks = "Auto Attacks"
 Truncate Method:

Western:
  1000=>1K,
  1000K=>1M
Asia East:
  10000=>1w = "Truncate Method:

Western:
  1000=>1K,
  1000K=>1M
Asia East:
  10000=>1w"
 Right = "Right"
 Embiggen Crits = "Embiggen Crits"
 Parried = "Parried"
 Immune = "Immune"
 Display Off-Target Text = "Display Off-Target Text"
 Shake = "Shake"
 Icon Scale = "Icon Scale"
 Let Masuqe skin the icons = "Let Masuqe skin the icons"
 Deflected = "Deflected"
 Personal SCT Only = "Personal SCT Only"
 Bottom = "Bottom"
 Scale down hits that are below a running average of your recent damage output = "Scale down hits that are below a running average of your recent damage output"
 Alpha = "Alpha"
 %s (A: %s) = "%s (A: %s)"
 Personal SCT = "Personal SCT"
 Reflected = "Reflected"
 Default Color = "Default Color"
 Default speed: 1 = "Default speed: 1"
 Bottom Right = "Bottom Right"
 Show Absorbed Damage = "Show Absorbed Damage"
 Show Truncated Letter = "Show Truncated Letter"
 Appearance/Offsets = "Appearance/Offsets"
 Display Overkill = "Display Overkill"
 Disabled = "Disabled"
 Hide hits that are below this threshold. = "Hide hits that are below this threshold."
 Hide Hits Threshold = "Hide Hits Threshold"
 High = "High"
 Randomly varies the starting vertical position of each damage number. = "Randomly varies the starting vertical position of each damage number."
 Y Variance = "Y Variance"
 Randomly varies the starting horizontal position of each damage number. = "Randomly varies the starting horizontal position of each damage number."
 Do Not Truncate = "Do Not Truncate"
 Use Crit Color = "Use Crit Color"
 X Variance = "X Variance"
 Enable Masque = "Enable Masque"
 Resisted = "Resisted"
 Crit Color = "Crit Color"
 Size = "Size"
 Hide hits that are below a running average of your recent damage output = "Hide hits that are below a running average of your recent damage output"
 Hide Small Hits = "Hide Small Hits"
 Small Hits Scale = "Small Hits Scale"
 Background = "Background"
 Embiggen Miss/Parry/Dodge/etc Scale = "Embiggen Miss/Parry/Dodge/etc Scale"
 Monochrome = "Monochrome"
 Icons = "Icons"
 Embiggen Miss/Parry/Dodge/etc = "Embiggen Miss/Parry/Dodge/etc"
 Low = "Low"
 Font = "Font"
 Default = "Default"
 Position = "Position"
 Thick Outline = "Thick Outline"
 Embiggen Crits Scale = "Embiggen Crits Scale"
 Has soft max/min, you can type whatever you'd like into the editbox = "Has soft max/min, you can type whatever you'd like into the editbox"
 Rainfall = "Rainfall"
 NPC id (eg: 23682) seperated by line

 The example is the Headless Horseman. = "NPC id (eg: 23682) seperated by line

 The example is the Headless Horseman."
 Criticals = "Criticals"
 Off-Target Strata = "Off-Target Strata"
 Off-Target Text Appearance = "Off-Target Text Appearance"
 Enable = "Enable"
 Icon X Offset = "Icon X Offset"
 Left = "Left"
 Top Right = "Top Right"
 Scale Down Small Hits = "Scale Down Small Hits"
 East Asia = "East Asia"
 Western = "Western"
 Target Strata = "Target Strata"
 Truncate Letter East Asia = "Truncate Letter East Asia"
 Truncate Number = "Truncate Number"
 Display Icon = "Display Icon"
 Text Shadow = "Text Shadow"
 Animation Speed = "Animation Speed"
 Only used if Personal Nameplate is Disabled = "Only used if Personal Nameplate is Disabled"
 Y Offset Personal SCT = "Y Offset Personal SCT"
 X Offset Personal SCT = "X Offset Personal SCT"
 Comma Seperate = "Comma Seperate"
 Monochrome Outline = "Monochrome Outline"
 Fountain = "Fountain"
 Icon Y Offset = "Icon Y Offset"
 Use
```
2:
```lua
1x AceLocale-3.0-6: NameplateSCT: Missing entry for 'Show Absorbed Damage shown as: '5 (A: 3)' where A: 3 is the absorbed amount'
[string "@NameplateSCT/NameplateSCT.lua"]:1266: in main chunk

Locals:
AceAddon = <table> {
 initializequeue = <table> {
 }
 statuses = <table> {
 }
 embeds = <table> {
 }
 frame = AceAddon30Frame {
 }
 addons = <table> {
 }
 enablequeue = <table> {
 }
}
LibEasing = <table> {
 frame = Frame {
 }
}
SharedMedia = <table> {
 OverrideMedia = <table> {
 }
 callbacks = <table> {
 }
 LOCALE_BIT_zhTW = 8
 LOCALE_BIT_ruRU = 2
 MediaType = <table> {
 }
 LOCALE_BIT_western = 128
 MediaTable = <table> {
 }
 LOCALE_BIT_zhCN = 4
 DefaultMedia = <table> {
 }
 MediaList = <table> {
 }
 LOCALE_BIT_koKR = 1
}
L = <table> {
 BlizzardSCT = "BlizzardSCT"
 Auto Attacks = "Auto Attacks"
 Truncate Method:

Western:
  1000=>1K,
  1000K=>1M
Asia East:
  10000=>1w = "Truncate Method:

Western:
  1000=>1K,
  1000K=>1M
Asia East:
  10000=>1w"
 Right = "Right"
 Embiggen Crits = "Embiggen Crits"
 Parried = "Parried"
 Immune = "Immune"
 Display Off-Target Text = "Display Off-Target Text"
 Shake = "Shake"
 Icon Scale = "Icon Scale"
 Let Masuqe skin the icons = "Let Masuqe skin the icons"
 Deflected = "Deflected"
 Personal SCT Only = "Personal SCT Only"
 Bottom = "Bottom"
 Scale down hits that are below a running average of your recent damage output = "Scale down hits that are below a running average of your recent damage output"
 Alpha = "Alpha"
 %s (A: %s) = "%s (A: %s)"
 Personal SCT = "Personal SCT"
 Reflected = "Reflected"
 Default Color = "Default Color"
 Default speed: 1 = "Default speed: 1"
 Show Absorbed Damage shown as: '5 (A: 3)' where A: 3 is the absorbed amount = "Show Absorbed Damage shown as: '5 (A: 3)' where A: 3 is the absorbed amount"
 Bottom Right = "Bottom Right"
 Show Absorbed Damage = "Show Absorbed Damage"
 Show Truncated Letter = "Show Truncated Letter"
 Appearance/Offsets = "Appearance/Offsets"
 Display Overkill = "Display Overkill"
 Disabled = "Disabled"
 Hide hits that are below this threshold. = "Hide hits that are below this threshold."
 Hide Hits Threshold = "Hide Hits Threshold"
 High = "High"
 Randomly varies the starting vertical position of each damage number. = "Randomly varies the starting vertical position of each damage number."
 Y Variance = "Y Variance"
 Randomly varies the starting horizontal position of each damage number. = "Randomly varies the starting horizontal position of each damage number."
 Do Not Truncate = "Do Not Truncate"
 Use Crit Color = "Use Crit Color"
 X Variance = "X Variance"
 Enable Masque = "Enable Masque"
 Resisted = "Resisted"
 Crit Color = "Crit Color"
 Size = "Size"
 Hide hits that are below a running average of your recent damage output = "Hide hits that are below a running average of your recent damage output"
 Hide Small Hits = "Hide Small Hits"
 Small Hits Scale = "Small Hits Scale"
 Background = "Background"
 Embiggen Miss/Parry/Dodge/etc Scale = "Embiggen Miss/Parry/Dodge/etc Scale"
 Monochrome = "Monochrome"
 Icons = "Icons"
 Embiggen Miss/Parry/Dodge/etc = "Embiggen Miss/Parry/Dodge/etc"
 Low = "Low"
 Font = "Font"
 Default = "Default"
 Position = "Position"
 Thick Outline = "Thick Outline"
 Embiggen Crits Scale = "Embiggen Crits Scale"
 Has soft max/min, you can type whatever you'd like into the editbox = "Has soft max/min, you can type whatever you'd like into the editbox"
 Rainfall = "Rainfall"
 NPC id (eg: 23682) seperated by line

 The example is the Headless Horseman. = "NPC id (eg: 23682) seperated by line

 The example is the Headless Horseman."
 Criticals = "Criticals"
 Off-Target Strata = "Off-Target Strata"
 Off-Target Text Appearance = "Off-Target Text Appearance"
 Enable = "Enable"
 Icon X Offset = "Icon X Offset"
 Left = "Left"
 Top Right = "Top Right"
 Scale Down Small Hits = "Scale Down Small Hits"
 East Asia = "East Asia"
 Western = "Western"
 Target Strata = "Target Strata"
 Truncate Letter East Asia = "Truncate Letter East Asia"
 Truncate Number = "Truncate Number"
 Display Icon = "Display Icon"
 Text Shadow = "Text Shadow"
 Animation Speed = "Animation Speed"
 Only used if Personal Nameplate is Disabled = "Only used if Personal Nameplate is Disabled"
 Y Offset Personal SCT = "Y Offset Personal SCT"
 X Offset Personal SCT = "X Off
 ```

**Comment by Nikyou** [comment]
Continued
3:
```lua
13x NameplateSCT/NameplateSCT.lua:898: attempt to compare number with nil
[string "@NameplateSCT/NameplateSCT.lua"]:898: in function `DamageEvent'
[string "@NameplateSCT/NameplateSCT.lua"]:762: in function <NameplateSCT/NameplateSCT.lua:738>
[string "=(tail call)"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 menu = Frame {
 }
 baseName = "NameplateSCT"
 name = "NameplateSCT"
 orderedModules = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleState = true
 frame = Frame {
 }
}
guid = "Creature-0-3110-2444-612-198594-0001A29A9C"
spellName = "Flame Shock"
amount = 10775
overkill = -1
school = 12
crit = false
spellId = 188389
absorbed = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
playerGUID = "Player-3391-0ADFD3C5"
guidToUnit = <table> {
 Creature-0-3110-2444-612-198594-0000229A9C = "nameplate5"
 Creature-0-3110-2444-612-194644-0000229A9C = "nameplate2"
 Creature-0-3110-2444-612-194648-0000229A9D = "nameplate1"
 Creature-0-3110-2444-612-198594-0001229A9C = "nameplate7"
 Creature-0-3110-2444-612-198594-0002229A9C = "nameplate9"
 Creature-0-3110-2444-612-194643-0000229A9C = "nameplate11"
 Creature-0-3110-2444-612-189632-0000229A9C = "nameplate10"
 Creature-0-3110-2444-612-198594-0001A29A9C = "nameplate8"
 Creature-0-3110-2444-612-198594-0000A29A9C = "nameplate6"
 Creature-0-3110-2444-612-197833-0000229A9D = "nameplate3"
}
NameplateSCT = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 menu = Frame {
 }
 baseName = "NameplateSCT"
 name = "NameplateSCT"
 orderedModules = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleState = true
 frame = Frame {
 }
}
L = <table> {
 BlizzardSCT = "BlizzardSCT"
 Auto Attacks = "Auto Attacks"
 Truncate Method:

Western:
  1000=>1K,
  1000K=>1M
Asia East:
  10000=>1w = "Truncate Method:

Western:
  1000=>1K,
  1000K=>1M
Asia East:
  10000=>1w"
 Right = "Right"
 Embiggen Crits = "Embiggen Crits"
 Parried = "Parried"
 Immune = "Immune"
 Display Off-Target Text = "Display Off-Target Text"
 Shake = "Shake"
 Icon Scale = "Icon Scale"
 Let Masuqe skin the icons = "Let Masuqe skin the icons"
 Deflected = "Deflected"
 Personal SCT Only = "Personal SCT Only"
 Bottom = "Bottom"
 Scale down hits that are below a running average of your recent damage output = "Scale down hits that are below a running average of your recent damage output"
 Alpha = "Alpha"
 %s (A: %s) = "%s (A: %s)"
 Personal SCT = "Personal SCT"
 Reflected = "Reflected"
 Default Color = "Default Color"
 Default speed: 1 = "Default speed: 1"
 Show Absorbed Damage shown as: '5 (A: 3)' where A: 3 is the absorbed amount = "Show Absorbed Damage shown as: '5 (A: 3)' where A: 3 is the absorbed amount"
 Bottom Right = "Bottom Right"
 Show Absorbed Damage = "Show Absorbed Damage"
 Show Truncated Letter = "Show Truncated Letter"
 Appearance/Offsets = "Appearance/Offsets"
 Display Overkill = "Display Overkill"
 Disabled = "Disabled"
 Hide hits that are below this threshold. = "Hide hits that are below this threshold."
 Hide Hits Threshold = "Hide Hits Threshold"
 High = "High"
 Randomly varies the starting vertical position of each damage number. = "Randomly varies the starting vertical position of each damage number."
 Y Variance = "Y Variance"
 Randomly varies the starting horizontal position of each damage number. = "Randomly varies the starting horizontal position of each damage number."
 Do Not Truncate = "Do Not Truncate"
 Use Crit Color = "Use Crit Color"
 X Variance = "X Variance"
 Enable Masque = "Enable Masque"
 Resisted = "Resisted"
 Crit Color = "Crit Color"
 Size = "Size"
 Hide hits that are below a running average of your recent damage output = "Hide hits that are below a running average of your recent damage output"
 Hide Small Hits = "Hide Small Hits"
 Small Hits Scale = "Small Hits Scale"
 Background = "Background"
 Embiggen Miss/Parry/Dodge/etc Scale = "Embiggen Miss/Parry/Dodge/etc Scale"
 Monochrome = "Monochrome"
 Icons = "Icons"
 Embiggen Miss/Parry/Dodge/etc = "Embig
 ```

**Comment by zbrak** [comment]
Similar - disabling askmrrobot addon but no difference.

```
423x NameplateSCT/NameplateSCT.lua:898: attempt to compare number with nil
[string "@NameplateSCT/NameplateSCT.lua"]:898: in function `DamageEvent'
[string "@NameplateSCT/NameplateSCT.lua"]:762: in function <NameplateSCT/NameplateSCT.lua:738>
[string "=(tail call)"]: ?
[string "@AskMrRobot/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:145: in function <...bot/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
[string "@AskMrRobot/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:90: in function `Fire'
[string "@AskMrRobot/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <AskMrRobot/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 menu = Frame {
 }
 baseName = "NameplateSCT"
 name = "NameplateSCT"
 orderedModules = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleState = true
 frame = Frame {
 }
}
guid = "Creature-0-4219-2444-2277-187494-000022B857"
spellName = "Conflagrate"
amount = 246
overkill = -1
school = 4
crit = false
spellId = 17962
absorbed = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
playerGUID = "Player-3678-0DCACDD8"
guidToUnit = <table> {
 Creature-0-4219-2444-2277-187494-000022B857 = "nameplate1"
}
NameplateSCT = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 menu = Frame {
 }
 baseName = "NameplateSCT"
 name = "NameplateSCT"
 orderedModules = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleState = true
 frame = Frame {
 }
}
L = <table> {
 BlizzardSCT = "BlizzardSCT"
 Auto Attacks = "Auto Attacks"
 Truncate Method:

Western:
  1000=>1K,
  1000K=>1M
Asia East:
  10000=>1w = "Truncate Method:

Western:
  1000=>1K,
  1000K=>1M
Asia East:
  10000=>1w"
 Right = "Right"
 Embiggen Crits = "Embiggen Crits"
 Parried = "Parried"
 Immune = "Immune"
 Display Off-Target Text = "Display Off-Target Text"
 Shake = "Shake"
 Icon Scale = "Icon Scale"
 Let Masuqe skin the icons = "Let Masuqe skin the icons"
 Deflected = "Deflected"
 Personal SCT Only = "Personal SCT Only"
 Bottom = "Bottom"
 Scale down hits that are below a running average of your recent damage output = "Scale down hits that are below a running average of your recent damage output"
 Alpha = "Alpha"
 %s (A: %s) = "%s (A: %s)"
 Personal SCT = "Personal SCT"
 Reflected = "Reflected"
 Default Color = "Default Color"
 Default speed: 1 = "Default speed: 1"
 Show Absorbed Damage shown as: '5 (A: 3)' where A: 3 is the absorbed amount = "Show Absorbed Damage shown as: '5 (A: 3)' where A: 3 is the absorbed amount"
 Bottom Right = "Bottom Right"
 Show Absorbed Damage = "Show Absorbed Damage"
 Show Truncated Letter = "Show Truncated Letter"
 Appearance/Offsets = "Appearance/Offsets"
 Display Overkill = "Display Overkill"
 Disabled = "Disabled"
 Hide hits that are below this threshold. = "Hide hits that are below this threshold."
 Hide Hits Threshold = "Hide Hits Threshold"
 High = "High"
 Randomly varies the starting vertical position of each damage number. = "Randomly varies the starting vertical position of each damage number."
 Y Variance = "Y Variance"
 Randomly varies the starting horizontal position of each damage number. = "Randomly varies the starting horizontal position of each damage number."
 Do Not Truncate = "Do Not Truncate"
 Use Crit Color = "Use Crit Color"
 X Variance = "X Variance"
 Enable Masque = "Enable Masque"
 Resisted = "Resisted"
 Crit Color = "Crit Color"
 Size = "Size"
 Hide hits that are below a running average of your recent damage output = "Hide hits that are below a running average of your recent damage output"
 Hide Small Hits = "Hide Small Hits"
 Small Hits Scale = "Small Hits Scale"
 Background = "Background"
 Embiggen Miss/Parry/Dodge/etc Scale = "Embiggen Miss/Parry/Dodge/etc Scale"
 Monochrome = "Monochrome"
 Icons = "Icons"
 Embiggen Miss/Parry/Dodge/etc = "Embiggen Miss/Parry/Dodge/etc"
 Low = "Low"
 Font = "Font"
 Default = "Default"
 Position = "Position"
 Thick Outline = "Thick Outline"
 Embiggen Crits Scale = "Embiggen Crits Scale"
 Has soft max/min, you can type whatever you'd like into the editbox = "Has soft max/min, you can type whatever you'd like into the editbox"
 Rainfall = "Rainfall"
 NPC id (eg: 23682) seperated by line

 The example is the Headless Horseman. = "NPC id (eg: 23682) seperated by line

 The example is the Headless Horseman."
 Criticals = "Criticals"
 Off-Targ
```

**Comment by Justw8** [comment]
@Nikyou What truncate method do you use?

the locale errors arn't stopping the addon from working.

**Comment by Nikyou** [comment]
@Justw8 Western

**Comment by hrlmartins** [comment]
Yup same as above. And as I get into combat it just keeps stacking up errors until out of combat. No text is seen from NSCT.

**Comment by Justw8** [comment]
What if you swap the truncate number setting to something else, and then back to western? does that fix it?

**Comment by zbrak** [comment]
(I cycled through all new locale options in my troubleshooting btw - no dice)

**Comment by Nikyou** [comment]
@Justw8 Nope

**Comment by Nikyou** [comment]
I can try and look into the code to see problem areas that make errors

**Comment by Justw8** [comment]
I think I have spotted the place why it goes wrong. I thought I fixed it but it looks like I messed something up somewhere.

**Comment by aromagnoli** [comment]
Same here! Exactly the same error.
```
1x AceLocale-3.0-6: NameplateSCT: Missing entry for 'Show Absorbed Damage shown as: '5 (A: 3)' where A: 3 is the absorbed amount'
[string "@NameplateSCT/NameplateSCT.lua"]:1266: in main chunk

Locals:
AceAddon = <table> {
 initializequeue = <table> {
 }
 statuses = <table> {
 }
 embeds = <table> {
 }
 frame = AceAddon30Frame {
 }
 addons = <table> {
 }
 enablequeue = <table> {
 }
}
LibEasing = <table> {
 frame = Frame {
 }
}
SharedMedia = <table> {
 OverrideMedia = <table> {
 }
 callbacks = <table> {
 }
 LOCALE_BIT_zhTW = 8
 LOCALE_BIT_ruRU = 2
 MediaType = <table> {
 }
 LOCALE_BIT_western = 128
 MediaTable = <table> {
 }
 LOCALE_BIT_zhCN = 4
 DefaultMedia = <table> {
 }
 MediaList = <table> {
 }
 LOCALE_BIT_koKR = 1
}
L = <table> {
 BlizzardSCT = "BlizzardSCT"
 Auto Attacks = "Auto Attacks"
 Truncate Method:

Western:
  1000=>1K,
  1000K=>1M
Asia East:
  10000=>1w = "Truncate Method:

Western:
  1000=>1K,
  1000K=>1M
Asia East:
  10000=>1w"
 Right = "Right"
 Embiggen Crits = "Embiggen Crits"
 Parried = "Parried"
 Immune = "Immune"
 Display Off-Target Text = "Display Off-Target Text"
 Shake = "Shake"
 Icon Scale = "Icon Scale"
 Let Masuqe skin the icons = "Let Masuqe skin the icons"
 Deflected = "Deflected"
 Personal SCT Only = "Personal SCT Only"
 Bottom = "Bottom"
 Scale down hits that are below a running average of your recent damage output = "Scale down hits that are below a running average of your recent damage output"
 Alpha = "Alpha"
 %s (A: %s) = "%s (A: %s)"
 Personal SCT = "Personal SCT"
 Reflected = "Reflected"
 Default Color = "Default Color"
 Default speed: 1 = "Default speed: 1"
 Show Absorbed Damage shown as: '5 (A: 3)' where A: 3 is the absorbed amount = "Show Absorbed Damage shown as: '5 (A: 3)' where A: 3 is the absorbed amount"
 Bottom Right = "Bottom Right"
 Show Absorbed Damage = "Show Absorbed Damage"
 Show Truncated Letter = "Show Truncated Letter"
 Appearance/Offsets = "Appearance/Offsets"
 Display Overkill = "Display Overkill"
 Disabled = "Disabled"
 Hide hits that are below this threshold. = "Hide hits that are below this threshold."
 Hide Hits Threshold = "Hide Hits Threshold"
 High = "High"
 Randomly varies the starting vertical position of each damage number. = "Randomly varies the starting vertical position of each damage number."
 Y Variance = "Y Variance"
 Randomly varies the starting horizontal position of each damage number. = "Randomly varies the starting horizontal position of each damage number."
 Do Not Truncate = "Do Not Truncate"
 Use Crit Color = "Use Crit Color"
 X Variance = "X Variance"
 Enable Masque = "Enable Masque"
 Resisted = "Resisted"
 Crit Color = "Crit Color"
 Size = "Size"
 Hide hits that are below a running average of your recent damage output = "Hide hits that are below a running average of your recent damage output"
 Hide Small Hits = "Hide Small Hits"
 Small Hits Scale = "Small Hits Scale"
 Background = "Background"
 Embiggen Miss/Parry/Dodge/etc Scale = "Embiggen Miss/Parry/Dodge/etc Scale"
 Monochrome = "Monochrome"
 Icons = "Icons"
 Embiggen Miss/Parry/Dodge/etc = "Embiggen Miss/Parry/Dodge/etc"
 Low = "Low"
 Font = "Font"
 Default = "Default"
 Position = "Position"
 Thick Outline = "Thick Outline"
 Embiggen Crits Scale = "Embiggen Crits Scale"
 Has soft max/min, you can type whatever you'd like into the editbox = "Has soft max/min, you can type whatever you'd like into the editbox"
 Rainfall = "Rainfall"
 NPC id (eg: 23682) seperated by line

 The example is the Headless Horseman. = "NPC id (eg: 23682) seperated by line

 The example is the Headless Horseman."
 Criticals = "Criticals"
 Off-Target Strata = "Off-Target Strata"
 Off-Target Text Appearance = "Off-Target Text Appearance"
 Enable = "Enable"
 Icon X Offset = "Icon X Offset"
 Left = "Left"
 Top Right = "Top Right"
 Scale Down Small Hits = "Scale Down Small Hits"
 East Asia = "East Asia"
 Western = "Western"
 Target Strata = "Target Strata"
 Truncate Letter East Asia = "Truncate Letter East Asia"
 Truncate Number = "Truncate Number"
 Display Icon = "Display Icon"
 Text Shadow = "Text Shadow"
 Animation Speed = "Animation Speed"
 Only used if Personal Nameplate is Disabled = "Only used if Personal Nameplate is Disabled"
 Y Offset Personal SCT = "Y Offset Personal SCT"
 X Offset Personal SCT = "X Off
 ```

**Comment by Justw8** [comment]
Please try v1.38 when it's up, if you still get errors with that version I can look again 👍

**Comment by kiruz-0** [comment]
When is v1.38 planned to be released? Seems like I'm having same issues like others. I cleared cache, settings variable and reinstalled addon but still the same error with absorb thing or nill value

**Comment by Justw8** [comment]
![image](https://github.com/user-attachments/assets/507a01d4-631d-470c-8014-a18fb9c104c9)

should be up any minute, you can also grab latest alpha. Has the same code, but not the version bump yet.

**Comment by zbrak** [comment]
You can also download the zip on github from the releases

**Comment by Justw8** [comment]
please let me know if it did fix it, then we can close this again.

**Comment by Justw8** [comment]
https://www.curseforge.com/wow/addons/nameplate-scrolling-combat-text/files/5566104

it's up there now too.

**Comment by aromagnoli** [comment]
Fixed it for me! \o/

**Comment by Justw8** [comment]
Closing this then thanks for reporting!

**Comment by hrlmartins** [comment]
It fixed partially for me got this error as soon as I attempted to do some damage to someone:

```lua
35x NameplateSCT/NameplateSCT.lua:925: attempt to compare number with nil
[string "@NameplateSCT/NameplateSCT.lua"]:925: in function `DamageEvent'
[string "@NameplateSCT/NameplateSCT.lua"]:771: in function <NameplateSCT/NameplateSCT.lua:739>
[string "=(tail call)"]: ?
[string "@Bartender4/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...er4/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Bartender4/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...er4/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Bartender4/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Bartender4/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Bartender4/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 menu = Frame {
 }
 baseName = "NameplateSCT"
 name = "NameplateSCT"
 orderedModules = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleState = true
 frame = Frame {
 }
}
guid = "Creature-0-1461-1-3834-5429-000022C886"
spellName = "Flame Shock"
amount = 3209187
overkill = 3207092
school = 12
crit = false
spellId = 188389
absorbed = nil
amount = 3209187
absorbed = 0
(*temporary) = nil
(*temporary) = 3209187
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
playerGUID = "Player-1403-098A4A10"
guidToUnit = <table> {
 Creature-0-1461-1-3834-5429-000022C886 = "nameplate1"
}
NameplateSCT = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 menu = Frame {
 }
 baseName = "NameplateSCT"
 name = "NameplateSCT"
 orderedModules = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleState = true
 frame = Frame {
 }
}
L = <table> {
 BlizzardSCT = "BlizzardSCT"
 Auto Attacks = "Auto Attacks"
 Truncate Method:

Western:
  1000=>1K,
  1000K=>1M
Asia East:
  10000=>1w = "Truncate Method:

Western:
  1000=>1K,
  1000K=>1M
Asia East:
  10000=>1w"
 Right = "Right"
 Embiggen Crits = "Embiggen Crits"
 Parried = "Parried"
 Immune = "Immune"
 Display Off-Target Text = "Display Off-Target Text"
 Shake = "Shake"
 Icon Scale = "Icon Scale"
 Let Masuqe skin the icons = "Let Masuqe skin the icons"
 Font Flags = "Font Flags"
 NPCs = "NPCs"
 Hide Small Hits = "Hide Small Hits"
 Bottom = "Bottom"
 Y Variance = "Y Variance"
 Scale down hits that are below a running average of your recent damage output = "Scale down hits that are below a running average of your recent damage output"
 Alpha = "Alpha"
 %s (A: %s) = "%s (A: %s)"
 Personal SCT = "Personal SCT"
 Reflected = "Reflected"
 Default Color = "Default Color"
 Default speed: 1 = "Default speed: 1"
 Show Absorbed Damage shown as: '5 (A: 3)' where A: 3 is the absorbed amount = "Show Absorbed Damage shown as: '5 (A: 3)' where A: 3 is the absorbed amount"
 Bottom Right = "Bottom Right"
 Y Offset = "Y Offset"
 Show Truncated Letter = "Show Truncated Letter"
 Appearance/Offsets = "Appearance/Offsets"
 Display Overkill = "Display Overkill"
 Disabled = "Disabled"
 Y Offset Personal SCT = "Y Offset Personal SCT"
 X Variance = "X Variance"
 High = "High"
 X Offset = "X Offset"
 X Offset Personal SCT = "X Offset Personal SCT"
 Western = "Western"
 Do Not Truncate = "Do Not Truncate"
 Use Crit Color = "Use Crit Color"
 Vertical Up = "Vertical Up"
 Enable Masque = "Enable Masque"
 Resisted = "Resisted"
 Vertical Down = "Vertical Down"
 Size = "Size"
 Rainfall = "Rainfall"
 Use Separate Off-Target Strata = "Use Separate Off-Target Strata"
 Use Damage Type Color = "Use Damage Type Color"
 Truncate Number = "Truncate Number"
 Truncate Letter East Asia = "Truncate Letter East Asia"
 Monochrome = "Monochrome"
 Hide hits that are below this threshold. = "Hide hits that are below this threshold."
 Top = "Top"
 Low = "Low"
 Font = "Font"
 Default = "Default"
 Position = "Position"
 Thick Outline = "Thick Outline"
 Text Shadow = "Text Shadow"
 Has soft max/min, you can type whatever you'd like into the editbox = "Has soft max/min, you can type whatever you'd like into the editbox"
 Bottom Left = "Bottom Left"
 Embiggen Crits Scale = "Embiggen Crits Scale"
 Top Left = "Top Left"
 Off-Target Strata = "Off-Target Strata"
 Off-Target Text Appearance = "Off-Target Text Appearance"
 Enable = "Enable"
 Criticals = "Criticals"
 Left = "Left"
 Top Right = "Top Right"
 Scale Down Small Hits = "Scale Down Small Hits"
 Icon X Offset = "Icon X Offset"
 Spells = "Spells"
 Target Strata = "Target Strata"
 Spellid/Spellname seperated by line

White hits/melee = melee = "Spellid/Spellname seperated by line

White hits/melee 
```

**Comment by Nikyou** [comment]
Same error

**Comment by Justw8** [comment]
yes please open a new issue if you still get an error with 1.38 please

**Comment by Justw8** [comment]
(I did just spot another issue with it, tagged 1.39)
